import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;



/**
 *
 * @author Lenovo
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AccNumTb = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        SubmitBtn.setBackground(new Color(102, 205, 170));
        AccNameTb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FaNameTb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PinTb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EducationTb = new javax.swing.JComboBox<>();
        OccupationTb = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PhoneTb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DobTb = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTb = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 180));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new Color(0, 0, 128));

        jLabel3.setFont(new Font("Centaur", Font.BOLD, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CENTRAL DHAKA BANK");

        jLabel8.setBackground(new java.awt.Color(255, 0, 102));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("x");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
        			.addContainerGap(298, Short.MAX_VALUE)
        			.addComponent(jLabel3)
        			.addGap(245)
        			.addComponent(jLabel8)
        			.addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        			.addGap(64))
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        			.addGap(20))
        );
        jPanel4.setLayout(jPanel4Layout);

        jLabel5.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel5.setForeground(new Color(0, 128, 0));
        jLabel5.setText("ACC NUM : ");

        jLabel6.setFont(new Font("Centaur", Font.BOLD, 18)); // NOI18N
        jLabel6.setForeground(new Color(0, 0, 205));
        jLabel6.setText("CENTRAL DHAKA BANK");

        AccNumTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AccNumTb.setForeground(new java.awt.Color(255, 102, 51));

        SubmitBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SubmitBtn.setForeground(new Color(178, 34, 34));
        SubmitBtn.setText("Submit");
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        AccNameTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AccNameTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel10.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel10.setForeground(new Color(0, 128, 0));
        jLabel10.setText("NAME : ");

        FaNameTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FaNameTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel11.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel11.setForeground(new Color(0, 128, 0));
        jLabel11.setText("FATHER'S NAME : ");

        PinTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PinTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel9.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel9.setForeground(new Color(0, 128, 0));
        jLabel9.setText("PIN : ");

        jLabel13.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel13.setForeground(new Color(0, 128, 0));
        jLabel13.setText("EDUCATION : ");

        EducationTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EducationTb.setForeground(new java.awt.Color(255, 102, 51));
        EducationTb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uneducated", "Matriculation", "Intermediate", "Diploma", "Under Graduate", "Post Graduate", "Ph.D" }));
        EducationTb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EducationTbItemStateChanged(evt);
            }
        });

        OccupationTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OccupationTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel14.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel14.setForeground(new Color(0, 128, 0));
        jLabel14.setText("OCCUPATION : ");

        jLabel15.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel15.setForeground(new Color(0, 128, 0));
        jLabel15.setText("PHONE : ");

        PhoneTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PhoneTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel16.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel16.setForeground(new Color(0, 128, 0));
        jLabel16.setText("JOB : ");

        DobTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DobTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel17.setFont(new Font("Serif", Font.BOLD, 12)); // NOI18N
        jLabel17.setForeground(new Color(0, 128, 0));
        jLabel17.setText("ADDRESS : ");

        AddressTb.setColumns(20);
        AddressTb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddressTb.setForeground(new java.awt.Color(255, 102, 51));
        AddressTb.setRows(5);
        jScrollPane1.setViewportView(AddressTb);

        jLabel1.setFont(new Font("Franklin Gothic Book", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new Color(220, 20, 60));
        jLabel1.setText("SIGNUP FORM");

        jPanel1.setBackground(new Color(220, 20, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(89)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel16)
        							.addPreferredGap(ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
        							.addComponent(DobTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel10)
        							.addGap(66)
        							.addComponent(AccNameTb, 166, 166, 166))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addGap(0, 0, Short.MAX_VALUE)
        							.addComponent(jLabel5)
        							.addGap(45)
        							.addComponent(AccNumTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel11)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(FaNameTb, 166, 166, 166)))
        					.addGap(116)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jLabel14)
        							.addGroup(jPanel3Layout.createSequentialGroup()
        								.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        									.addComponent(jLabel13, Alignment.LEADING)
        									.addComponent(jLabel15, Alignment.LEADING))
        								.addGap(116)))
        						.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(jPanel3Layout.createSequentialGroup()
        								.addComponent(jLabel9)
        								.addGap(77)
        								.addComponent(PinTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))
        							.addComponent(EducationTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
        							.addComponent(OccupationTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
        							.addComponent(PhoneTb, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)))
        					.addGap(90))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel17)
        					.addGap(46)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 566, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(0, 369, Short.MAX_VALUE)
        			.addComponent(SubmitBtn)
        			.addGap(367))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(348, Short.MAX_VALUE)
        			.addComponent(jLabel6)
        			.addGap(296))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(377, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(353))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        			.addGap(17)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(jPanel3Layout.createSequentialGroup()
        						.addGap(6)
        						.addComponent(jLabel9))
        					.addComponent(jLabel5, Alignment.TRAILING)
        					.addComponent(AccNumTb, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(PinTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(EducationTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel13))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel14)
        						.addComponent(OccupationTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel15)
        						.addComponent(PhoneTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel10)
        						.addComponent(AccNameTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel11)
        						.addComponent(FaNameTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(DobTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel16))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel17)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
        			.addComponent(SubmitBtn)
        			.addGap(18)
        			.addComponent(jLabel6)
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void EducationTbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EducationTbItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_EducationTbItemStateChanged

    Connection con = null;
    PreparedStatement put = null;
    ResultSet Rs = null;
    Statement st = null;
    private void clear(){
        AccNumTb.setText("");
        AccNameTb.setText("");
        FaNameTb.setText("");
        EducationTb.setSelectedIndex(-1);
        OccupationTb.setText("");
        AddressTb.setText("");
        PhoneTb.setText("");
        PinTb.setText("");
        DobTb.setText("");
    }
    
    
    
   private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked 
    if(AccNumTb.getText().isEmpty() || AccNameTb.getText().isEmpty() || FaNameTb.getText().isEmpty() || OccupationTb.getText().isEmpty() || PhoneTb.getText().isEmpty() || AddressTb.getText().isEmpty() || DobTb.getText().isEmpty() || PinTb.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information!");
    } else {
        // Get all the entered data
        String accountNumber = AccNumTb.getText();
        String accountName = AccNameTb.getText();
        String fatherName = FaNameTb.getText();
        String dob = DobTb.getText();
        String phone = PhoneTb.getText();
        String address = AddressTb.getText();
        String education = EducationTb.getSelectedItem().toString();
        String occupation = OccupationTb.getText();
        String pin = PinTb.getText();

        // Display the entered data in a message dialog
        String message = "Account Number: " + accountNumber + "\n"
                       + "Account Name: " + accountName + "\n"
                       + "Father's Name: " + fatherName + "\n"
                       + "Date of Birth: " + dob + "\n"
                       + "Phone: " + phone + "\n"
                       + "Address: " + address + "\n"
                       + "Education: " + education + "\n"
                       + "Occupation: " + occupation + "\n"
                       + "Pin: " + pin;

        // Show the message dialog
        JOptionPane.showMessageDialog(this, message, "Entered Information", JOptionPane.INFORMATION_MESSAGE);

        // Clear the form fields
        clear();

        // Open the login window
        new Login().setVisible(true);

        // Close the signup window
        this.dispose();
    }
}
    
    
    
    
    
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccNameTb;
    private javax.swing.JTextField AccNumTb;
    private javax.swing.JTextArea AddressTb;
    private javax.swing.JTextField DobTb;
    private javax.swing.JComboBox<String> EducationTb;
    private javax.swing.JTextField FaNameTb;
    private javax.swing.JTextField OccupationTb;
    private javax.swing.JTextField PhoneTb;
    private javax.swing.JTextField PinTb;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}