import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;



/**
 *
 * @author Lenovo
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Shashi
 */
public class Withdraw extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    public Withdraw() {
        initComponents();
    }
    int MyAccNumt;
    public Withdraw(int AccNum) {
        initComponents();
        MyAccNumt = AccNum;
        getBalance();
    }
    Connection con = null;
    ResultSet Rs = null, Rs1=null;
    Statement st = null;
    int OldBalalnce;
    
    private void getBalance(){
        String query = "Select * from accounttbl where AccNum ="+MyAccNumt+";";
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","system");
                st = con.createStatement();
                Rs1 = st.executeQuery(query);
                if(Rs1.next()){
                    OldBalalnce = Rs1.getInt(9);
                    BalanceLb.setText(""+OldBalalnce);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBackground(new Color(255, 222, 173));
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AmountTb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JLabel();
        balanceBtn = new javax.swing.JButton();
        balanceBtn.setBackground(new Color(0, 139, 139));
        jLabel11 = new javax.swing.JLabel();
        BalanceLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(360, 180));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new Color(0, 0, 128));

        jLabel2.setFont(new Font("MS Reference Sans Serif", Font.BOLD, 24)); // NOI18N
        jLabel2.setForeground(new Color(245, 222, 179));
        jLabel2.setText("ATM MANAGEMENT SYSTEM");

        jLabel7.setBackground(new Color(50, 205, 50));
        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 36)); // NOI18N
        jLabel7.setForeground(new Color(255, 255, 0));
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new Font("Centaur", Font.BOLD, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CENTRAL DHAKA BANK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(361)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 309, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(264)
        			.addComponent(jLabel7)
        			.addGap(575))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jLabel5.setFont(new Font("Perpetua Titling MT", Font.BOLD, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("AMOUNT : ");

        AmountTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AmountTb.setForeground(new java.awt.Color(255, 102, 51));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("WITHDRAW YOUR CASH ");

        LogoutBtn.setFont(new Font("Microsoft YaHei", Font.BOLD, 18)); // NOI18N
        LogoutBtn.setForeground(new Color(178, 34, 34));
        LogoutBtn.setText("LOGOUT");
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseClicked(evt);
            }
        });

        balanceBtn.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        balanceBtn.setForeground(new Color(255, 0, 0));
        balanceBtn.setText("WITHDRAW");
        balanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balanceBtnMouseClicked(evt);
            }
        });
        balanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new Font("Verdana", Font.PLAIN, 20)); // NOI18N
        jLabel11.setForeground(new Color(0, 0, 205));
        jLabel11.setText("Your Balance : ");

        BalanceLb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BalanceLb.setForeground(new java.awt.Color(0, 0, 204));
        
        panel_1 = new JPanel();
        panel_1.setBackground(new Color(85, 107, 47));
        panel_1.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 1575, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(282)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel11)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel10)
        					.addPreferredGap(ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
        					.addComponent(BalanceLb, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
        					.addGap(265))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(AmountTb, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(balanceBtn, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 1016, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(559, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(450)
        			.addComponent(LogoutBtn, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(981, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel10)
        			.addGap(69)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(BalanceLb, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel11))
        			.addGap(32)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(AmountTb, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(balanceBtn)
        				.addComponent(jLabel5))
        			.addGap(35)
        			.addComponent(LogoutBtn, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        			.addGap(65)
        			.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1017, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(595, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 506, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceBtnActionPerformed

    private void LogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseClicked
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutBtnMouseClicked

    private void clear(){
        AmountTb.setText("");
    }
    
    String MyDate;
    
    public void getDateTime(){
        LocalDateTime today = LocalDateTime.now();
        DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        MyDate = today.format(formater);
    }
    
    private void withdrawMoney(){
        try{
                getDateTime();
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","system");
                PreparedStatement Add = con.prepareStatement("insert into transactiontbl (AccNum, Type, Amount, TDate) VALUES (?, ?, ?, ?)");
                Add.setInt(1, MyAccNumt);
                Add.setString(2, "Withdraw");
                Add.setString(3, AmountTb.getText());
                Add.setString(4, MyDate);
                int row = Add.executeUpdate();
                con.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
    }
    
    private void balanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balanceBtnMouseClicked
        if(AmountTb.getText().isEmpty() || AmountTb.getText().equals("0") ){
            JOptionPane.showMessageDialog(this, "Enter Valid Amount!");
            clear();
        }else if(Integer.valueOf(AmountTb.getText())>OldBalalnce){
            JOptionPane.showMessageDialog(this, "Insufficient Balaance!");
            clear();
        }else{
            String query = "Update accounttbl set Balance=? where AccNum=?";
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","system");
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1, OldBalalnce-Integer.valueOf(AmountTb.getText()));
                ps.setInt(2, MyAccNumt);
                if(ps.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, "Withdraw Successful.");
                    withdrawMoney();
                    clear();
                    getBalance();
                }else{
                    JOptionPane.showMessageDialog(this, "Missing Information!");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }  
        }
    }//GEN-LAST:event_balanceBtnMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTb;
    private javax.swing.JLabel BalanceLb;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JButton balanceBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JPanel panel_1;
    // End of variables declaration//GEN-END:variables
}